[package]
name = "lococo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.26.0"
clap = "4.5.21"
dotenv = "0.15.0"
git2 = "0.19.0"
